### ISSUE TITLE
css sprite

### ISSUE THREAD

**Issue by maboiteaspam** [slaterjohn/payment-logos#1]
Hi!

How about adding support for css sprites ?

With the help of 
https://github.com/Ensighten/grunt-spritesmith
and optimize pictures with
https://github.com/gruntjs/grunt-contrib-imagemin

?

**Comment by slaterjohn** [comment]
@maboiteaspam That's not a bad idea. I'll get that added in to a later release :)

**Comment by maboiteaspam** [comment]
up to u

**Comment by slaterjohn** [comment]
@maboiteaspam If you'd like to create a pull request for the changes you requested i'd be happy to review :)

**Comment by slaterjohn** [comment]
@maboiteaspam There is now a sprite ready made as part of this repo. I haven't generated a CSS file for it however it's on my to-do list.

https://github.com/slaterjohn/payment-logos/commit/9ee54deeeb66e1f59a60aefba229acf7e266c0dd
